version: '2.4'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - proxied
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./conf.d:/etc/nginx/conf.d

  dockergen:
    image: jwilder/docker-gen
    networks:
      - proxied
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    depends_on:
      - nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    env_file:
      - default.env

networks:
  proxied:
    name: proxied