version: '2'
services:
  nginx:
    image: nginx
    container_name: nginx
    network_mode: host
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - /etc/nginx/conf.d

  dockergen:
    image: jwilder/docker-gen
    network_mode: host
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    # env_file:
    #   - default.env

  # whoami:
  #   image: jwilder/whoami
  #   environment:
  #     - VIRTUAL_HOST=whoami.local