version: '2.4'
services:
  nginx:
    image: nginx
    container_name: nginx
    network_mode: host
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./conf.d:/etc/nginx/conf.d

  dockergen:
    image: jwilder/docker-gen
    network_mode: host
    restart: always
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    env_file:
      - default.env
