version: '3.7'
services:
  anyproxy:
    image: leeyanzhe/anyproxy
    ports:
      - 8118:8118
    restart: always
    command: ["anyproxy", "--port", "8118", "--ignore-unauthorized-ssl"]
    env_file:
      - web.env
