version: '2.4'
services:
  anyproxy:
    image: leeyanzhe/anyproxy
    volumes:
    network_mode: host
    restart: always
    mem_limit: 200000000
    # memswap_limit: 2000000000
    command: ["anyproxy", "--port", "8118"]
