version: '3.7'
services:
  anyproxy:
    image: leeyanzhe/anyproxy
    network_mode: host
    restart: always
    command: ["anyproxy", "--port", "8118", "--ignore-unauthorized-ssl"]
    env_file:
      - web.env
