version: '2.4'
services:
  omnisci-ce:
    image: omnisci/core-os-cuda
    ports: 
      - '6273-6280:6273-6280'
    container_name: omnisci-ce
    volumes:
      - ./omnisci-storage:/omnisci-storage
    restart: always
    # runtime: nvidia
  omnisci-ee:
    image: omnisci/omnisci-ee-cuda
    ports:
      - '6273-6280:6273-6280'
    container_name: omnisci-ee
    volumes:
      - ./omnisci-storage:/omnisci-storage
    restart: always
    env_file:
      - web.env
    # runtime: nvidia
