version: '2.4'
services:
  v2ray-s:
    image: v2ray/official
    container_name: v2ray-s
    expose:
      - 80
    restart: always
    volumes:
      - ./config.json:/etc/v2ray/config.json
    env_file:
      - web.env
  v2ray-c:
    image: v2ray/official
    container_name: v2ray-c
    network_mode: host
    restart: always
    volumes:
      - ./config.json:/etc/v2ray/config.json
