version: '3.6'
services:
  v2ray:
    image: v2ray/official
    networks:
      - proxied
    expose:
      - 80
    restart: always
    volumes:
      - ./config.json:/etc/v2ray/config.json
    env_file:
      - web.env