version: '2.4'
services:
  v2ray-s:
    image: v2fly/v2fly-core
    container_name: v2ray-s
    network_mode: host
    restart: always
    volumes:
      - ./config.json:/etc/v2ray/config.json
      - ./ssl:/etc/v2ray/ssl
  v2ray-c:
    image: v2fly/v2fly-core
    container_name: v2ray-c
    network_mode: host
    restart: always
    volumes:
      - ./config.json:/etc/v2ray/config.json
