version: '2.4'
services:
  v2ray-s:
    image: leeyanzhe/v2ray:latest
    container_name: v2ray-s
    network_mode: host
    restart: always
    volumes:
      - ./config.json:/etc/v2ray/config.json
      - /var/run/v2ray:/var/run/v2ray
    env_file:
      - web.env
  v2ray-c:
    image: leeyanzhe/v2ray:latest
    container_name: v2ray-c
    network_mode: host
    restart: always
    volumes:
      - ./config.json:/etc/v2ray/config.json
