version: '3.6'
services:
  nfs:
    image: itsthenetwork/nfs-server-alpine
    volumes:
      - /data:/nfsshare
    restart: always
    network_mode: host
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SETPCAP
    environment:
      - SHARED_DIRECTORY=/nfsshare