version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ee
    container_name: gitlab
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    restart: always
    hostname: git.hitnslab.com
    env_file:
      - web.env
