version: '2.4'
services:
  trojan:
    image: trojangfw/trojan:latest
    container_name: trojan
    restart: always
    network_mode: host
    volumes:
      - ./config.json:/etc/trojan/config.json
      - ./ssl:/etc/trojan/ssl
