version: '3.6'
services:
  docker-mirror:
    image: registry:2
    volumes:
      - ./repos/docker/data:/var/lib/registry
      - ./repos/docker/config.yml:/etc/config.yml
    restart: always
    command: /etc/config.yml
    env_file:
      - ./repos/docker/web.env
