version: '3.6'
services:
  v2-mirror:
    image: registry:2
    network_mode: host
    volumes:
      - ./data:/var/lib/registry
      - ./config.yml:/etc/config.yml
    restart: always
    command: /etc/config.yml
    env_file:
      - web.env
