version: '2.4'
services:
  gitlab-mirror:
    image: registry:2
    volumes:
      - ./repos/gitlab/data:/var/lib/registry
      - ./repos/gitlab/config.yml:/etc/config.yml
    restart: always
    command: /etc/config.yml
    env_file:
      - ./repos/gitlab/web.env
