version: '2.4'
services:
  frps:
    image: leeyanzhe/frp
    network_mode: host
    container_name: frps
    volumes:
      - ./frps.ini:/etc/frp/frps.ini
    restart: always
    command:
      - frps
      - -c
      - frps.ini
  frpc:
    image: leeyanzhe/frp
    network_mode: host
    container_name: frpc
    volumes:
      - ./frpc.ini:/etc/frp/frpc.ini
    restart: always
    command:
      - frpc
      - -c
      - frpc.ini