version: '3.6'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "MY_PASSWORD"
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
volumes:
  mysql_db:
