version: '3.6'
services:
  sslocal:
    image:
      mritd/shadowsocks
    container_name: sslocal
    secrets:
      - sslocal
    restart: always
    network_mode: host
    #ports:
    #  - target: 1080
    #    published: 1080
    #    protocol: tcp
    #  - target: 1080
    #    published: 1080
    #    protocol: udp
    environment:
      SS_CONFIG: "-c /run/secrets/sslocal -v"
      SS_MODULE: "ss-local"
  ssserver:
    image:
      mritd/shadowsocks
    container_name: ssserver
    secrets:
      - ssserver
    restart: always
    network_mode: host
    environment:
      SS_CONFIG: "-c /run/secrets/ssserver -v"
      SS_MODULE: "ss-server"
secrets:
  sslocal:
    file: ./sslocal.json
  ssserver:
    file: ./ssserver.json
