version: '3.6'
services:
  keepalived:
    image: osixia/keepalived
    network_mode: host
    cap_add:
      - NET_ADMIN
    restart: always
    volumes:
      - ./keepalived.conf:/usr/local/etc/keepalived/keepalived.conf
      - ./scripts/myscript.sh:/etc/keepalived/myscript.sh